### PR TITLE
Ores rework

### PR DESCRIPTION
**Pull request by TheNoty**
Changed default ores to new textures from latest minecraft vanilla version, Put quartz into stone rather than netherack, redid all the custom ores blocks and items.

### CODE REVIEW

**Comment by MicleBrick** [comment]
Quartz is only found in stone on quod canis, it's left as netherrack because it's mostly on Cerus Alpha and Orcus in netherrack

**Comment by MicleBrick** [comment]
these are mostly good except I don't like the new cheth ore texture as much as the old one

**Comment by TheNoty** [comment]
> these are mostly good except I don't like the new cheth ore texture as much as the old one

What about it?

**Comment by MicleBrick** [comment]
too angular in one direction & focused on top right corner I suppose

**Comment by TheNoty** [comment]
> too angular in one direction & focused on top right corner I suppose

the ore block?

**Comment by MicleBrick** [comment]
yes

**Pull request closed without merging**
